#!/bin/bash

echo "Select:"
echo "-----------------------"
echo "|    IF  INPUT PORT   | "
echo "----------------------|"
echo "| 1 - Analogic port 1 |"
echo "| 2 - Analogic port 2 |"
echo "| 3 - Digital port/s  |"
echo "-----------------------"
echo "     ACTIVATED         "
echo "-----------------------"
echo -ne "Choose Port : "
read -r iport
case $iport in
1)
echo ""
echo "Choose value considering 0=off & 255=on"
echo ""
echo -ne "Input a value between 0 & 255 : "
read -r ipvanl1

if [[ -z $ipvan1 ]]
then
exit 1
fi

echo ""
echo "Select :"
echo "-------------------------"
echo "| THEN  ACTIVATE OUTPUT |"
echo "-------------------------"
echo "| 1 - Analogic port 1   |"
echo "| 2 - Analogic port 2   |"
echo "| 3 - Digital port/s    |"
echo "-------------------------"
echo -ne "Choose Port : "
read -r oport

if [[ "$oport" == "1" ]]
then
echo ""
echo "Choose value considering 0=off & 255=on"
echo ""
echo -ne "Input a value between 0 & 255 : "
read -r opvan1
if [[ -z $opvan1 ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "ia1 $ipvan1 oa1 $opvan1" >> rules.txt
else
echo "ia1 $ipvan1 oa1 $opvan1" > rules.txt
fi
fi
if [[ "$oport" == "2" ]]
then
echo ""
echo "Choose value considering 0=off & 255=on"
echo ""
echo -ne "Input a value between 0 & 255 : "
read -r opvan2
if [[ -z $opvan2 ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "ia1 $ipvan1 oa1 $opvan2" >> rules.txt
else
echo "ia1 $ipvan1 oa1 $opvan2" > rules.txt
fi
fi
if [[ "$oport" == "3" ]]
then
echo ""
echo "Choose 1 or more outputs ports from 1 to 8"
echo "example : 147 - to activate ports 1 ,4 & 7"
echo -ne "Input ports numbers : "
read -r opvdg
if [[ -z $opvdg ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "ia1 $ipvan1 od $opvdg" >> rules.txt
else
echo "ia1 $ipvan1 od $opvdg" > rules.txt
fi
fi
echo ""
sleep 5
exit 1
;;
2)
echo ""
echo "Choose value considering 0=off & 255=on"
echo ""
echo -ne "Input a value between 0 & 255 : "
read -r ipvanl2
if [[ -z $ipvan2 ]]
then
exit 1
fi
echo ""
echo "Select :"
echo "-------------------------"
echo "| THEN  ACTIVATE OUTPUT |"
echo "-------------------------"
echo "| 1 - Analogic port 1   |"
echo "| 2 - Analogic port 2   |"
echo "| 3 - Digital port/s    |"
echo "-------------------------"
echo -ne "Choose Port : "
read -r oport
if [[ "$oport" == "1" ]]
then
echo ""
echo "Choose value considering 0=off & 255=on"
echo ""
echo -ne "Input a value between 0 & 255 : "
read -r opvan1
if [[ -z $opvan1 ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "ia2 $ipvan2 oa1 $opvan1" >> rules.txt
else
echo "ia2 $ipvan2 oa1 $opvan1" > rules.txt
fi
fi
if [[ "$oport" == "2" ]]
then
echo ""
echo "Choose value considering 0=off & 255=on"
echo ""
echo -ne "Input a value between 0 & 255 : "
read -r opvan2
if [[ -z $opvan2 ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "ia2 $ipvan2 oa1 $opvan2" >> rules.txt
else
echo "ia2 $ipvan2 oa1 $opvan2" > rules.txt
fi
fi
if [[ "$oport" == "3" ]]
then
echo ""
echo "Choose 1 or more outputs ports from 1 to 8"
echo "example : 147 - to activate ports 1 ,4 & 7"
echo -ne "Input port/s number/r : "
read -r opvdg
if [[ -z $opvdg ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "ia2 $ipvan2 od $opvdg" >> rules.txt
else
echo "ia2 $ipvan2 od $opvdg" > rules.txt
fi
fi
echo ""
sleep 5
exit 1
;;
3)
echo ""
echo "Choose a Digital input port 1 & 5"
echo ""
echo -ne "Port Input : "
read -r ipvdg
if [[ -z $ipvdg ]]
then
exit 1
fi
echo ""
echo "Select :"
echo "-------------------------"
echo "| THEN  ACTIVATE OUTPUT |"
echo "-------------------------"
echo "| 1 - Analogic port 1   |"
echo "| 2 - Analogic port 2   |"
echo "| 3 - Digital port/s    |"
echo "-------------------------"
echo -ne "Choose Port : "
read -r oport
if [[ "$oport" == "1" ]]
then
echo ""
echo "Choose value considering 0=off & 255=on"
echo ""
echo -ne "Input a value between 0 & 255 : "
read -r opvan1
if [[ -z $opvan1 ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "id $ipvdg oa1 $opvan1" >> rules.txt
else
echo "id $ipvdg oa1 $opvan1" > rules.txt
fi
fi
if [[ "$oport" == "2" ]]
then
echo ""
echo "Choose value considering 0=off & 255=on"
echo ""
echo -ne "Input a value between 0 & 255 : "
read -r opvan2
if [[ -z $opvan2 ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "id $ipvdg oa1 $opvan2" >> rules.txt
else
echo "id $ipvdg oa1 $opvan2" > rules.txt
fi
fi
if [[ "$oport" == "3" ]]
then
echo ""
echo "Choose 1 or more outputs ports from 1 to 8"
echo "example : 147 - to activate ports 1 ,4 & 7"
echo -ne "Input port/s number/r : "
read -r opvdg
if [[ -z $opvdg ]]
then
exit 1
fi
if [[ -f rules.txt ]]
then
echo "id $ipvdg od $opvdg" >> rules.txt
else
echo "id $ipvdg od $opvdg" > rules.txt
fi
fi
echo ""
sleep 5
exit 1
;;
*)
exit 1
;;
esac